services:
  - type: web
    name: youtube-tutorial-scraper
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: COSMOS_ENDPOINT
        sync: false
      - key: COSMOS_KEY
        sync: false
      - key: COSMOS_DATABASE_NAME
        value: YouTubeTutorials
      - key: COSMOS_CONTAINER_NAME
        value: tutorials
